{{- if .Values.test.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "squid.fullname" . }}-test
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
  {{- if not .Values.mirrord.enabled }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "squid.fullname" . }}-test
  labels:
    {{- include "squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
  {{- if not .Values.mirrord.enabled }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "squid.fullname" . }}-test
  labels:
    {{- include "squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
  {{- if not .Values.mirrord.enabled }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "squid.fullname" . }}-test
subjects:
- kind: ServiceAccount
  name: {{ include "squid.fullname" . }}-test
  namespace: {{ .Values.namespace.name }}
{{- end }} 
