# Start from an official Fedora 42 image
FROM registry.fedoraproject.org/fedora:42

# DNF tuning from official Podman Containerfile for build robustness
RUN echo -e "\\n\\n# Added during image build" >> /etc/dnf/dnf.conf && \
    echo -e "minrate=100\\ntimeout=60\\n" >> /etc/dnf/dnf.conf

# Install dependencies for the dev environment
ARG INSTALL_RPMS="podman openssh-clients cpp git-core golang which procps-ng curl helm kubernetes1.33-client jq hadolint gh"
RUN dnf -y makecache && \
    dnf -y update && \
    dnf -y install $INSTALL_RPMS --exclude container-selinux && \
    dnf clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.*

# Install kind, mage, ginkgo CLI, and dlv debugger 
RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64 && \
    chmod +x ./kind && \
    mv ./kind /usr/local/bin/kind && \
    GOBIN=/usr/local/bin go install github.com/magefile/mage@v1.15.0 && \
    GOBIN=/usr/local/bin go install github.com/onsi/ginkgo/v2/ginkgo@latest && \
    GOBIN=/usr/local/bin go install github.com/go-delve/delve/cmd/dlv@latest

# Install mirrord binary securely from GitHub releases (specific version)
ARG MIRRORD_VERSION=3.150.0
RUN curl -fsSL "https://github.com/metalbear-co/mirrord/releases/download/${MIRRORD_VERSION}/mirrord_linux_x86_64" -o /usr/local/bin/mirrord && \
    chmod +x /usr/local/bin/mirrord

# Create a non-root user 'vscode' to run as, and grant it passwordless sudo.
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

# Add Go bin directory to the vscode user's PATH
# Ignoring hadolint because in this case we don't want variables expanded during
# the container build.
# hadolint ignore=SC2016
RUN echo 'export PATH="$PATH:$HOME/go/bin"' >> /home/$USERNAME/.bashrc

# Switch to the non-root user
USER $USERNAME
